# Generated by Django 5.2.16 on 2026-08-09 09:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_default_drone(apps, schema_editor):
    DroneProfile = apps.get_model("missions", "DroneProfile")
    DroneProfile.objects.get_or_create(
        slug="f450-pixhawk-rpi-imx477",
        defaults={
            "display_name": "F450 + Pixhawk 2.4.8 + RPi (Sony IMX477)",
            "manufacturer": "Custom",
            "max_speed_ms": Decimal("12.00"),
            "max_altitude_m": Decimal("120.00"),
            "sensor_width_mm": Decimal("6.287"),
            "sensor_height_mm": Decimal("4.712"),
            "focal_length_mm": Decimal("6.000"),
            "image_width_px": 4056,
            "image_height_px": 3040,
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Identifikator')),
                ('display_name', models.CharField(max_length=120, verbose_name='Prikazno ime')),
                ('manufacturer', models.CharField(blank=True, max_length=64, verbose_name='Proizvajalec')),
                ('max_speed_ms', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='Najv. hitrost [m/s]')),
                ('max_altitude_m', models.DecimalField(decimal_places=2, default=Decimal('120'), max_digits=6, verbose_name='Najv. visina [m]')),
                ('sensor_width_mm', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Sirina senzorja [mm]')),
                ('sensor_height_mm', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Visina senzorja [mm]')),
                ('focal_length_mm', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Goriscna razdalja [mm]')),
                ('image_width_px', models.PositiveIntegerField(verbose_name='Sirina slike [px]')),
                ('image_height_px', models.PositiveIntegerField(verbose_name='Visina slike [px]')),
            ],
            options={
                'verbose_name': 'Profil drona',
                'verbose_name_plural': 'Profili dronov',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='TestFlightSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude_m', models.FloatField(default=3.0, verbose_name='Višina [m]')),
                ('hover_s', models.FloatField(default=5.0, verbose_name='Lebdenje [s]')),
                ('countdown_s', models.FloatField(default=5.0, verbose_name='Odštevanje [s]')),
                ('min_satellites', models.PositiveSmallIntegerField(default=10, verbose_name='Najmanj satelitov')),
                ('max_hdop', models.FloatField(default=1.5, verbose_name='Največji HDOP')),
                ('require_gps', models.BooleanField(default=True, verbose_name='Zahtevaj GPS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Posodobljeno')),
            ],
            options={
                'verbose_name': 'Nastavitve testnega poleta',
                'verbose_name_plural': 'Nastavitve testnega poleta',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ime misije')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('home_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Vzletisce sirina')),
                ('home_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Vzletisce dolzina')),
                ('home_alt_amsl_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Vzletisce AMSL [m]')),
                ('altitude_mode', models.CharField(choices=[('AGL', 'Relativno glede na vzletisce (AGL)'), ('AMSL', 'Absolutno nad morsko gladino (AMSL)')], default='AGL', max_length=4, verbose_name='Referenca visine')),
                ('default_altitude_m', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=6, verbose_name='Privzeta visina [m]')),
                ('default_speed_ms', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5, verbose_name='Privzeta hitrost [m/s]')),
                ('finish_action', models.CharField(choices=[('HOVER', 'Lebdenje na zadnji tocki'), ('RTH', 'Vrnitev domov (RTH)'), ('LAND', 'Pristanek')], default='RTH', max_length=8, verbose_name='Dejanje ob koncu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='missions.droneprofile', verbose_name='Drone')),
            ],
            options={
                'verbose_name': 'Misija',
                'verbose_name_plural': 'Misije',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Vrstni red')),
                ('element_type', models.CharField(choices=[('WP', 'Waypoint'), ('MAP', 'Mapping zone')], max_length=4, verbose_name='Tip')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Oznaka')),
                ('altitude_m', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Visina [m]')),
                ('speed_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hitrost [m/s]')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Sirina')),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Dolzina')),
                ('heading_mode', models.CharField(blank=True, choices=[('AUTO', 'Sledi smeri leta'), ('FIXED', 'Fiksna smer'), ('POI', 'Cilj zanimanja (POI)'), ('NEXT_WP', 'Proti naslednjemu waypointu')], default='AUTO', max_length=8, verbose_name='Nacin smeri')),
                ('heading_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('360'))], verbose_name='Smer [°]')),
                ('gimbal_pitch_deg', models.DecimalField(decimal_places=2, default=Decimal('-90'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('30'))], verbose_name='Naklon gimbala [°]')),
                ('path_style', models.CharField(blank=True, choices=[('STRAIGHT', 'Ravno (ustavi v tocki)'), ('CURVED', 'Krivo (zaobide tocko)')], default='STRAIGHT', max_length=8, verbose_name='Pot do tocke')),
                ('action_type', models.CharField(blank=True, choices=[('NONE', 'Brez dejanja'), ('PHOTO', 'Foto'), ('VIDEO_START', 'Zacni snemanje'), ('VIDEO_STOP', 'Ustavi snemanje'), ('CAPTURE_BURST', 'Burst zajem')], default='NONE', max_length=16, verbose_name='Dejanje')),
                ('hover_time_s', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='Cas lebdenja [s]')),
                ('polygon_geojson', models.JSONField(blank=True, null=True, verbose_name='Poligon (GeoJSON)')),
                ('pattern', models.CharField(blank=True, choices=[('GRID', 'Obicajen'), ('CROSSHATCH', 'Mreza')], default='GRID', max_length=10, verbose_name='Vzorec')),
                ('front_overlap_pct', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(95)], verbose_name='Vzd. prekrivanje [%]')),
                ('side_overlap_pct', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(95)], verbose_name='Prec. prekrivanje [%]')),
                ('track_angle_deg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Smer prog [°]')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='missions.mission', verbose_name='Misija')),
            ],
            options={
                'verbose_name': 'Gradnik',
                'verbose_name_plural': 'Gradniki',
                'ordering': ['mission_id', 'order'],
                'constraints': [models.UniqueConstraint(fields=('mission', 'order'), name='uniq_element_order_per_mission')],
            },
        ),
        migrations.RunPython(seed_default_drone, migrations.RunPython.noop),
    ]
